# Generated by Django 5.1.5 on 2025-01-27 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('company', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('website', models.URLField()),
            ],
        ),
    ]
